### ISSUE TITLE
Piece flip feature

### ISSUE THREAD

**Issue by ufo2mstar** [scoutant/blokish#10]
Hi! Nice game.. recently played blokus and was interested in the strategy!

One issue I notice is that flipping/reversing pieces is not possible (or if it is possible, I haven't figured out how to do it yet)
I would like to see that as one of the options which i feel i do all the time in the physical game..
One way to do it that I would approach from a user UI perspective is adding a mirror option along with the Cross and Check mark so that the piece is flipped.. 
Once I have some free time I would like to add it to the code myself, but if anyone else is able to get to it before, that would be great too!
Cheers..
![blo1](https://cloud.githubusercontent.com/assets/2426264/8510468/238bc0aa-22b4-11e5-8f8f-4d62f1060a1c.png)
![blo2](https://cloud.githubusercontent.com/assets/2426264/8510469/2934c1f0-22b4-11e5-99fd-37e587585aec.png)

**Comment by ufo2mstar** [comment]
You know what.. i as soon as i posted I looked at the code and realized that long pressing flips the pieces..lol nevamind!

**Comment by scoutant** [comment]
Absolutely.
