### ISSUE TITLE
Clicking light grey circles to flip pieces ?   or some flip buttons ? 

### ISSUE THREAD

**Issue by digitaldoctors** [scoutant/blokish#16]
![blokish flip pieces](https://cloud.githubusercontent.com/assets/24817437/21533925/fccfbdf6-cd2d-11e6-9345-1ff89eb29acc.jpg)

Please consider a more intuitive UI for flipping pieces.

Great app otherwise.  Thanks !!!

**Comment by scoutant** [comment]
Thanks for suggestion. Those handles are used for rotation purpose.
I understand long-press is not most intuitive. I would need to add additional icon four only flip purpose. I do so for next release.
