### ISSUE TITLE
Size increased too much at 3.1 -> 3.2

### ISSUE THREAD

**Issue by ildar** [scoutant/blokish#19]
From 0.5 to 2.2MB
Why?

**Comment by gilcot** [comment]
I'm using the F-Droid app and noticed the same thing:
- version 3.1: 512 KiB
- version 3.2: 2.2 MiB

Then I check the changelog: only a brazilian locale added; can't see what makes the size increase so so much

**Comment by scoutant** [comment]
True, only locale added. But now compiled against SDK Android 8.1 (API 27).

**Comment by ildar** [comment]
I see. That must be the support jar

**Comment by gilcot** [comment]
I can't understand why the issue is closed but still unsolved
