### ISSUE TITLE
Game Play Doesn't Reset or Restart  Upon Exit , Hence Providing No Means To Start A New Game..

### ISSUE THREAD

**Issue by organik1** [scoutant/blokish#24]
#### Expected behavior
One would expect the app to restart and provide a new frame on which they can start a new game after exiting and relaunching the app. 

#### Actual behavior
The app doesn't restart after exit, instead it is back to last state with all the moves and changes still intact upon relaunch. In other words, if a player had moved two blocks or any number of block, even after exiting the game and relaunching, those moves are still intact.

#### How to reproduce
* Launch Blokish
* Play the game for a while.
* Exit the game
* And then relaunch.

### Testing Environment.

* Browser:  Google Chrime
* Operating system: Android Version 7 (Nougat)
* App Version: Blokish v3.2

#### Recording Of The Bug
![20180313215702.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520975413/xf20ohmnwmh1dvzv9tjg.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@organik/game-play-doesn-t-reset-or-restart-upon-exit-hence-providing-no-means-to-start-a-new-game">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by scoutant** [comment]
Yes the game does save the state enabling you to pause and resume. Even after device restart.
To resume a new game just use menu you can open with the drawer : a left to right gesture.

**Comment by scoutant** [comment]
An if you enable Android 9 gesture navigation the drawer menu can be opened sliding with 45 degre gesture
